### ISSUE TITLE
Chapter 8 ENV SECRETE_KEY in docker-compose

### ISSUE THREAD

**Issue by ericchou1** [wsvincent/djangoforprofessionals#1]
It seems that some characters have problems being paste-in to the docker-compose file. Searched around and people either have to use ENV in Dockerfile or .env then reference it in docker-compose via ${}.

$ docker-compose down
WARNING: The s variable is not set. Defaulting to a blank string.
ERROR: Invalid interpolation format for "environment" option in service "web": "SECRET_KEY=<skip>"

Just want to make a note of it if somebody else come across the same issue.

**Comment by wsvincent** [comment]
Yes, this is correct. I've updated in the new versions of the book. Thanks for highlighting this @ericchou1 !
