### ISSUE TITLE
Heroku Django media not loading

### ISSUE THREAD

**Issue by rpalloni** [wsvincent/djangoforprofessionals#101]
Django for Professional is a great book. 
Only three things I would have added are:
- a related_name explanation (around page 224)
- a mention to django_cleanup in ch 12 File/Image uploads
-  the automatic creation in Heroku of the config var DATABASE_URL that explains your settings of DATABASE in settings.py.

However, a big thing is missing: Heroku does not allow to handle media as explained here: https://stackoverflow.com/questions/61894188/heroku-django-images-not-loading
I think you should at least mention the fact that there is 0MB in Heroku for your media.

PS: also a pdf-version-after-buy of the book would be cool as it would help with quick search of specific things (e.g. DATABASE_URL.....)

**Comment by wsvincent** [comment]
Hi @rpalloni,

Thanks for the feedback. Finishing up the 4.0 update at the moment...

- yup, added related_name explanation. There's a bunch to unpack there so thank you for the prompt. Adding it.
- agree on django-cleanup. I've added it to the "Next Steps" section at the end of the File/Image chapter
- very good point on media files on Heroku... I'm adding more to the File/Image chapter and Deployment on this.

Did you buy the Amazon version btw? If you did and want pdf access, email me directly with your receipt (will@wsvincent.com) and I can provide digital access.

Cheers,

Will

**Comment by rpalloni** [comment]
Found a workaround here as regards Heroku
https://stackoverflow.com/questions/46692520/how-to-upload-files-into-binaryfield-using-filefield-widget-in-django-admin

Email you for the version 4.0

**Comment by wsvincent** [comment]
Hi Roberto,

Thank you for this great feedback. I actually implemented all 3 of your
changes in the 4.1 update I'm working on now. So thank you for that! And
for alerting me to django_cleanup which was new to me but seems great.

Cheers,

Will
