### ISSUE TITLE
Chapter 11: Foreign Keys

### ISSUE THREAD

**Issue by MrigankShekhar2** [wsvincent/djangoforprofessionals#152]
> A one-to-many relationship is far more common and is the default foreign key setting within
Django. For example, one student can sign up for many classes.

Is that example one-to-many or many-to-many? Because a class may belong to more than one student.

**Comment by wsvincent** [comment]
Hi @MrigankShekhar2 ,

Good pt. It really depends how you configure your models but that example could be improved to be less confusing. Working on that now for the 4.0 update. 

Cheers,

Will
