### ISSUE TITLE
Remove the file db.sqlite3 from the repo

### ISSUE THREAD

**Issue by marianobrc** [wsvincent/djangoforprofessionals#162]
The SQLite database file shouldn't be committed in the repo. Also, I believe SQLite isn't used anymore after chapter 1, but the file is there in every chapter's directory here.

**Comment by wsvincent** [comment]
Good points. It's not a good practice to have SQLite files in source control. It's in future chapters cause not in a .gitignore and created by default on the initial project. I'm working on the 4.0 update and will make sure no SQLite files are included. Thanks for mentioning this!
