### ISSUE TITLE
Media Files directory

### ISSUE THREAD

**Issue by aetaylor** [wsvincent/djangoforprofessionals#170]
Hi Will,

I'm working my way through Django for Professionals v4.0 and all had been going smoothly until Chapter 13.
I'm not sure whether it's due to a typo or my misunderstanding.

The text states: "We can add both of these settings after STATICFILES_FINDERS near the bottom of the django_- project/settings.py file. We’ll use the common convention of calling both media."

I have no STATICFILES_FINDERS in my settings file, so I followed the code here in GitHub and placed the lines beneath the other STATICxxx lines.

I'm not sure what you mean by "We’ll use the common convention of calling both media" since one line specifies "media" and the other specifies "static".

I set my MEDIA_ROOT = BASE_DIR / "media" since this matched the following instructions regarding the creation of a "media" directory with a "covers" subdirectory, but the project in GitHub does not contains these folders; it seems to be placing the uploaded images in "static/covers".

Could you please clarify what should be happening with regards to placing the uploaded images in either the "static" folder or the "media" folder?

**Comment by wsvincent** [comment]
Hi @aetaylor,

Thank you for this feedback. Another readers has noted the same. It is an unfortunate double typo on my end:
- `STATICFILES_FINDERS` should be `STATICFILES_STORAGE` which we set in Ch7
- `MEDIA_ROOT = BASE_DIR / "media"` is correct, not with "static" as in the book

I've fixed both issues now for future editions so hopefully it doesn't impact many other readers!
