### ISSUE TITLE
Chapter 10 book_detail.html missing opening <a>

### ISSUE THREAD

**Issue by ericchou1** [wsvincent/djangoforprofessionals#2]
page 207 book_detail.html: 

```
<h2>{{ book.title }}</a></h2>
```

Missign ```<a href="">``` as indicated in code repository.

**Comment by wsvincent** [comment]
I'm having trouble finding this, Eric. Can you provide more code or an image of this?

**Comment by wsvincent** [comment]
Nevermind, found it. Thanks for the sharp eyes!
