### ISSUE TITLE
Chapter 8 aullauth logout redirect issue

### ISSUE THREAD

**Issue by eroicaleo** [wsvincent/djangoforprofessionals#205]
Hi Will,

In chapter 8 `django_project/settings.py`, I think we should probably make the following changes.

```diff
-ACCOUNT_LOGOUT_REDIRECT = "home"
+ACCOUNT_LOGOUT_REDIRECT_URL = "home"
```

Otherwise, if we set the following, it will not redirect us to the about page.

```
ACCOUNT_LOGOUT_REDIRECT = "about"
```

**Comment by wsvincent** [comment]
Hi @eroicaleo, Thanks for the Issue. If you want to redirect to the About page then what you've done here would work. I believe in the book it says the redirect just goes to the homepage though so I think things are correct as is unless I'm missing something.

Closing this for now but please reopen if I'm in error!

**Comment by foodcourt2021** [comment]
@wsvincent 

Hi Will,

Sorry for the confusion! My point is, we need to add `_URL` at the end of `ACCOUNT_LOGOUT_REDIRECT` to make
the redirect work.

```diff
-ACCOUNT_LOGOUT_REDIRECT = "home"
+ACCOUNT_LOGOUT_REDIRECT_URL = "home"
```

**Comment by eroicaleo** [comment]
@wsvincent

Hi Will,

Sorry for the confusion! My point is, we need to add `_URL` at the end of `ACCOUNT_LOGOUT_REDIRECT` to make
the redirect work.

```diff
-ACCOUNT_LOGOUT_REDIRECT = "home"
+ACCOUNT_LOGOUT_REDIRECT_URL = "home"
```

**Comment by wsvincent** [comment]
Ah, you are correct! Hmm, I wonder how that happened. But nonetheless you are right and I will be updating this for the forthcoming update. Thanks for taking the time to correct me :)
