### ISSUE TITLE
Invalid Link

### ISSUE THREAD

**Issue by aualby** [wsvincent/djangoforprofessionals#206]
Hi Will,

    Great books. 

    Page 99 of DFP, bottom of the page, Images, the link is not found, 404.

   https://github.com/wsvincent/djangoforprofessionals/blob/main/dfp.png

**Comment by wsvincent** [comment]
Hi @aualby,

Thanks for the Issue. The link is https://github.com/wsvincent/djangoforprofessionals/blob/main/dfp.jpg . I'm not sure if you have an older version of the book or if the issue is on my end. All the links in the current edition are for dfp.jpg not dfp.png.

-Will
