### ISSUE TITLE
Issue with docker-compose.yml

### ISSUE THREAD

**Issue by gschuell** [wsvincent/djangoforprofessionals#45]
When I created the Dockerfile and docker-compose.yml files, I cannot get the docker-compose up command to work. The yml line command: python /code/manage.py runserver 0.0.0.0:8000 fails. When I changed it to command: python /code/hello/manage.py runserver 0.0.0.0:8000 I am able to run the app in docker. I am running on Mac OS X 10.15.3 with Docker version 2.2.0.3.

**Comment by mehtez** [comment]
I have also problems running the commands like in the book. I think there is something mixed up with the folders. 

First we have to mkdir /code/hello/ and then he does not tell in the book where to start the Docker commands. Or where to put the Dockerfile. One does not know in which directory he currently is, when he tells to start the commands. There is just the $ sign, absolutely no idea where I am with it.

**Comment by gschuell** [comment]
Hi Mehmet,

I was able to get the hello sample app running on docker. There were errors the way the yml file was printed in the book, plus for some reason the Pipfile.lock and Pipfile didn’t seem to be in the right place. I copied them under the code folder.

Here is the contents of my code folder:


I created the code folder under by home directory rather than the desktop. Here is my Dockerfile and the docker-compose.yml.
 Dockerfile

# Pull base image

FROM python:3.8

# Set environment variables

ENV PYTHONDONTWRITEBYTECODE 1

ENV PYTHONBUFFERED 1

# Set work directory

WORKDIR /code

# Install dependencies

COPY Pipfile Pipfile.lock /code/

RUN pip install pipenv && pipenv install --system

# Copy project

COPY . /code/



docker-compose.yml

version: '3.7'
services:
  web:
    build: .
    command: python /code/hello/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000

I run everything from the code directory.

Hope this helps.

Regards,

George Schueller

**Comment by mehtez** [comment]
Thanks, I tried a bunch of directories now and it still doesn't work. 

After the docker-compose up command it says 

`Recreating hello_web_1 ... done`
`Attaching to hello_web_1`
`web_1  | python: can't open file '/hello/hello_project/manage.py': [Errno 2] No such file or directory`
`hello_web_1 exited with code 2`

No matter how I change the directory it can not find the file. I'm on Windows and don't know how to write down the directory tree right. I tried it also with backslashes, but that doesn't work either.

**Comment by gregkepler** [comment]
@mehtez was there anything helpful in the logs? 
To see them type: `docker-compose logs`

**Comment by Ahmed-ao** [comment]
when i'm trying to execute commands within docker they never works!, for instance the command 
**$ docker-compose exec web python manage.py startapp users**
from the third chapter in django for professionals.
returns: 
**CommandError:** 'users' conflicts with the name of an existing Python module and cannot be used as an app name. Please try another name.!!!
however I changed the app's name to be customers, this time nothing showed up on the screen and no app had been created.!
is anyone of you  went through something related?

**Comment by guyellery** [comment]
Hi,

My issue is similar...
When I run docker-compose up, I get the following:
$ docker-compose up
Recreating hello_web_1 ... done 
Attaching to hello_web_1
web_1  | Watching for file changes with StatReloader
web_1  | Performing system checks...
web_1  |
web_1  | System check identified no issues (0 silenced).
web_1  | March 29, 2020 - 13:41:35

and it stops at that point. In the book it shows a further 3 lines...
web_1 | Django version 3.0, using settings 'hello_project.settings'
web_1 | Starting development server http://0.0.0.0:8000
web_1 | Quit the server qith CONTROL-C

I DO NOT get those last 3 lines. Consequently, when I run http://0.0.0.0:8000 (I also tried http://127.0.0.1:8000) I get the error message:

This site can’t be reached
0.0.0.1 refused to connect.

Can anyone help?
Regards,
GuyE

**Comment by stoan** [comment]
> 
> 
> Hi,
> 
> My issue is similar...
> When I run docker-compose up, I get the following:
> $ docker-compose up
> Recreating hello_web_1 ... done
> Attaching to hello_web_1
> web_1 | Watching for file changes with StatReloader
> web_1 | Performing system checks...
> web_1 |
> web_1 | System check identified no issues (0 silenced).
> web_1 | March 29, 2020 - 13:41:35
> 
> and it stops at that point. In the book it shows a further 3 lines...
> web_1 | Django version 3.0, using settings 'hello_project.settings'
> web_1 | Starting development server http://0.0.0.0:8000
> web_1 | Quit the server qith CONTROL-C
> 
> I DO NOT get those last 3 lines. Consequently, when I run http://0.0.0.0:8000 (I also tried http://127.0.0.1:8000) I get the error message:
> 
> This site can’t be reached
> 0.0.0.1 refused to connect.
> 
> Can anyone help?
> Regards,
> GuyE

Did you check your docker logs? 

`$ docker logs hello_web_1 `

[Docker Logs](https://docs.docker.com/engine/reference/commandline/logs/)

**Comment by guyellery** [comment]
Hi Siya,

Thanks for the really quick response!

This is what I get from the command:

eller@DESKTOP-2CGUEHV MINGW64 /c/Program Files/Docker Toolbox
$ docker logs hello_web_1
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
March 29, 2020 - 16:44:16
Django version 3.0, using settings 'hello_project.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

eller@DESKTOP-2CGUEHV MINGW64 /c/Program Files/Docker Toolbox

I checked from a different session whilst I had docker-compose up running from a different session. So it looks like it did it get through to those last 3 lines even though it did not display it.

However, when I then run the web address I get this still:

[cid:b6dcdec7-9801-4114-80a5-99fbecb245e1]

I also tried the following:
docker-compose.yml line changed from command: python /code/manage.py runserver 0.0.0.0:8000 to command: python /code/manage.py runserver 127.0.0.1:8000
then CONTROL-C and docker-compose down. Saved the changes to the .yml and then docker-compose up. Still would not connect.

I also tried various combinations of the above to no avail.

Again, I am at a loss of what to try next. The log says its running hello_project.settings.py... is there something I can do from there?

Regards,
Guy Ellery

________________________________

**Comment by guyellery** [comment]
Hi Siya,

I think I have resolved this (further chapters in the book will prove it). This is what I did...
1) Delete / Drop everything and start from scratch EXCEPT the initial installation of Docker. Note that this is for Docker Toolbox on Windows 10 Home Edition.
2) Follow everything exactly from Chapter 1 PP12 through to the end of PP26. Test with docker-compose up and STILL THE SAME ISSUE. CONTROL-C to quit out and run docker-compose down to ensure you are completely out.
3) Back to PP12 and run this docker run -p 80:80 nginx INSTEAD OF the book code "docker run hello-world". (This seems to link to a different virtual connector - I am going to research this a bit more to understand it better!)
4) Run this: docker-machine ip default to get the ip address --> 192.168.99.100
5) Change hello_project.settings.py ALLOWED_HOSTS = [] to ALLOWED_HOSTS = ['*']
6) Run docker-compose up. This time I GET THE LAST 3 LINES!!!
7) On the browser, type http://192.168.99.100:8000/ and this returns Hello World!. I tested that it is the right one by changing the text of Hello World and it displayed the new text.
8) Test again by stopping the Docker service - CONTROL-C / docker-compose down. Web page fails. Re-start with docker-compose up and refresh the web page - Hello World appears.

So I "THINK" this is now working but wherever the book mentions the web page 127.0.0.1:8000 I need to use http://192.168.99.100:8000/ instead.

Please let me know if this is something I SHOULD NOT be doing.

Regards,
GuyE

**Comment by guyellery** [comment]
Final Update...

$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
4f7e5a5f3977        hello_web           "python /code/manage…"   2 hours ago         Up 2 hours          0.0.0.0:8000->8000/tcp   hello_web_1
1e48ee26e188        nginx               "nginx -g 'daemon of…"   2 hours ago         Up 2 hours          0.0.0.0:80->80/tcp       jovial_brattain

Shows that the expected "hello_web_1" and new "jovial_brattain" (thats a random generated name) container services are running.

Using docker-compose down ONLY stops the hello_web image. The nginx image is still running. If you want to stop that use the docker stop with a timeout command.

Thanks.
GuyE

**Comment by Muhammadnadeem123456** [comment]
when i access listview from our main products categories give "Cannot resolve keyword '' into field. Choices are: category, id, image, name"
