### ISSUE TITLE
python: can't open file '/code/manage.py'

### ISSUE THREAD

**Issue by aurphillus** [wsvincent/djangoforprofessionals#46]
Unable to get the docker running, followed all the steps. Using windows

`$ docker-compose up
Recreating code_web_1 ... done                                                                                          Attaching to code_web_1
web_1  | python: can't open file '/code/manage.py': [Errno 2] No such file or directory
code_web_1 exited with code 2`

**Comment by RaccoonForever** [comment]
Hello :)

Solution : put all your app code on C:/Users/USERNAME/...

It seems that it doesn't work on another drive than C

**Comment by YashMarmat** [comment]
Hi..

i think your manage.py file is present inside your bookstore_project folder. Your manage.py file needs to be in that folder where your bookstore_project folder is present. You maybe ignored the period at the end of the below command 
`django-admin startproject django bookstore_project .`

now putting that manage.py with your bookstore_project manually i dont think will work, still you can try it. But most likely you need to run the command again or start the project again with the command given above.
