### ISSUE TITLE
Any workarounds for Windows 10 Home?

### ISSUE THREAD

**Issue by jasonsalas** [wsvincent/djangoforprofessionals#47]
I'm greatly enjoying all three books on Django, but I'm on Windows 10 Home, so the required Docker install is proving quick tricky. With the _Django for Beginners_ book, I got the demos to run using virtualenv instead of pipenv, so I'm hoping for some sort of similar workaround, even if remotely, for this book, which otherwise is outstanding. Anyone have any ideas?

**Comment by AndyPestellNCL** [comment]
Hi Jasonsalas - not sure if it will help, but I'm using Docker Toolbox, which is a lighter version of Docker - my installation of Windows wouldn't run the full Docker.

**Comment by rashearman** [comment]
I tried Docker Toolbox on Windows 10 Home and couldn't get it to work properly. I abandoned trying to get Windows to work and just created a VM by installing Ubuntu inside VirtualBox. I installed Docker Engine in the VM and so far so good!

**Comment by jasonsalas** [comment]
Thanks, @AndyPestellNCL! Were you able to get the book demos to run properly?

**Comment by YashMarmat** [comment]
try dual boot you pc with linux os (example: ubuntu), all linux os works very fine with docker :)
