### ISSUE TITLE
chapter 2, problem when changed the database settings 

### ISSUE THREAD

**Issue by YashMarmat** [wsvincent/djangoforprofessionals#48]
all worked fine but when i tried to change database from sqlite3 to postgresql and went to django local host page it still saying Problem reloading the page (Note: i followed all command till the topic: New Database of chapter 2). Also, i recieved this error when i ran this command -> docker-compose logs

Attaching to pgresql_web_1, pgresql_db_1
web_1  | Watching for file changes with StatReloader
web_1  | Performing system checks...
web_1  | 
web_1  | System check identified no issues (0 silenced).
web_1  | Exception in thread django-main-thread:
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
web_1  |     self.connect()
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
web_1  |     self.connection = self.get_new_connection(conn_params)
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
web_1  |     connection = Database.connect(**conn_params)
web_1  |   File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
db_1   | Error: Database is uninitialized and superuser password is not specified.
web_1  |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
db_1   |        You must specify POSTGRES_PASSWORD to a non-empty value for the
web_1  | psycopg2.OperationalError: could not translate host name "db" to address: Name or service not known
db_1   |        superuser. For example, "-e POSTGRES_PASSWORD=password" on "docker run".
web_1  | 
db_1   | 
web_1  | 
db_1   |        You may also use "POSTGRES_HOST_AUTH_METHOD=trust" to allow all
web_1  | The above exception was the direct cause of the following exception:
db_1   |        connections without a password. This is *not* recommended.
web_1  | 
db_1   | 
web_1  | Traceback (most recent call last):
db_1   |        See PostgreSQL documentation about "trust":
web_1  |   File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
web_1  |     self.run()
db_1   |        https://www.postgresql.org/docs/current/auth-trust.html
web_1  |   File "/usr/local/lib/python3.6/threading.py", line 864, in run
web_1  |     self._target(*self._args, **self._kwargs)
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/utils/autoreload.py", line 54, in wrapper
web_1  |     fn(*args, **kwargs)
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 120, in inner_run
web_1  |     self.check_migrations()
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 453, in check_migrations
web_1  |     executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 18, in __init__
web_1  |     self.loader = MigrationLoader(self.connection)
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/migrations/loader.py", line 49, in __init__
web_1  |     self.build_graph()
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/migrations/loader.py", line 212, in build_graph
web_1  |     self.applied_migrations = recorder.applied_migrations()
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 73, in applied_migrations
web_1  |     if self.has_table():
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 56, in has_table
web_1  |     return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 256, in cursor
web_1  |     return self._cursor()
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 233, in _cursor
web_1  |     self.ensure_connection()
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
web_1  |     self.connect()
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
web_1  |     raise dj_exc_value.with_traceback(traceback) from exc_value
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
web_1  |     self.connect()
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
web_1  |     self.connection = self.get_new_connection(conn_params)
web_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
web_1  |     connection = Database.connect(**conn_params)
web_1  |   File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
web_1  |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
web_1  | django.db.utils.OperationalError: could not translate host name "db" to address: Name or service not known
web_1  |

**Comment by YashMarmat** [comment]
finally !!!! it worked 
after spending two days with this issue (frustating hours of my life) i finally resolved this issue,
if you are facing it too then put the following code in your docker-compose.yml file.
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust" 

Note: after applying the above code the local host server can still show the same error but just run that migration command (as in my case i got this error when i tried to run migrations, before that New Database topic of chapter2) mentioned in the book which are:

after changes run below command in terminal (according to book)
    docker-compose exec web python manage.py migrate
then
    docker-compose exec web python manage.py createsuperuser

**Comment by wsvincent** [comment]
Hi @YashMarmat , Thank you for posting your solution here. I updated that very recently in the book and you can see it in the code base but hadn't been able to respond to your PR. Docker made this breaking change very recently, a frustrating thing. Glad you sorted it out! -Will

**Comment by samsime** [comment]
> finally !!!! it worked
> after spending two days with this issue (frustating hours of my life) i finally resolved this issue,
> if you are facing it too then put the following code in your docker-compose.yml file (just below image:postgres11).
> 
> environment:
> - "POSTGRES_HOST_AUTH_METHOD=trust"
> 
> Note: after applying the above code the local host server can still show the same error but just run that migration command (as in my case i got this error when i tried to run migrations, before that New Database topic of chapter2) mentioned in the book which are:
> 
> after changes run below command in terminal (according to book)
> `docker-compose exec web python manage.py migrate`
> then
> `docker-compose exec web python manage.py createsuperuser`

for my case, in addition to what you said, I also add 
expose:
      - "5432"
I add it just before environment in the db service. And it works perfectly.

according to the page 
https://stackoverflow.com/questions/51750715/could-not-translate-host-name-db-to-address-using-postgres-docker-compose-and
