### ISSUE TITLE
 djangoforprofessionals/ch6-static-assets/templates/_base.html  minor typos bugs

### ISSUE THREAD

**Issue by jaq19** [wsvincent/djangoforprofessionals#6]
I found the following bugs/typos in your code in the directory:
 djangoforprofessionals/ch6-static-assets/templates/_base.html 

1- missing open h5 tagin line 16
  <a href="{. . .- normal">Bookstore</h5>

2- missing closing div tags in the end of line 25-28 which i assume it should go after line 26 closing the nav tag. 

Please correct those errors and if i am wrong please let me know, i am new to programing and i need to learn. Thank you.

**Comment by wsvincent** [comment]
You are quite right on both these counts. Well spotted! I've updated the text and the code here to reflect the changes. Thanks so much for taking the time to let me--and other readers--know.

**Comment by jaq19** [comment]
Thank you so very much for your reply, i have enjoyed all your django
books, i started using django for begginers and for APIs and now i am
almost done with django for professionals, and I'd like to thank you for
writing such great books, i have enjoyed them and i have learned a lot from
your books. If i had a suggestion, i noticed that your projects are purely
focused on functionality and proper configuration which is crucial for real
production projects, but if you ever have a chance i would really like to
see a book that shows styling and more structural pages. I am very new to
this, and i need to be able to write fully functional as well as good
looking websites. If you have any suggestions for any good books to
accomplish that would be greatly appreciated. Thank you so much and i hope
to see more book materials from you soon.

**Comment by wsvincent** [comment]
Hmm, I agree I don't go that deep on design in the books beyond using Bootstrap. There's just a ton of different resources out there. I'd recommend spending some time on pure CSS first. FreeCodeCamp is a nice resource for example. Try to recreate popular websites yourself. Also look into CSS Grids. WesBos has a course that is free: https://cssgrid.io. So basically do the fundamentals and then get into Bootstrap/Tailwind/other frameworks as needed :)
