### ISSUE TITLE
Using Docker in Windows 7 is pain! python: can't open file '/code/manage.py'

### ISSUE THREAD

**Issue by hazartilirot** [wsvincent/djangoforprofessionals#64]
Good day everyone,

I don't want to duplicate text here so.... I got many problems with Docker. It's my third day I've been fighting with them.... A book for beginners was really easy-peasy.... As soon as I started reading for Professionals I was overwhelmed with the problems.

https://stackoverflow.com/questions/62348686/i-cant-start-my-docker-container-on-windows-7/

**Comment by hazartilirot** [comment]
Well, I close the thread since most of my problems I solved on my own.

**Comment by wsvincent** [comment]
Hi @hazartilirot ,

So unfortunately this was a Docker Windows bug that came up recently. Not really related to the book. Frustrating for me, as the author, since I used Docker in part to remove issues around Mac/Windows/Linux.

I'm glad you seemed to sort it out.

Best,

Will
