### ISSUE TITLE
No guarantee that Dockerfile and piplock will be compatible, leading to error installing psychopg2

### ISSUE THREAD

**Issue by DaveParr** [wsvincent/djangoforprofessionals#68]
I ran into an error, which I've fixed, but that could be a trap for new users. It stems from having a system install of python 3.8, and the book (sample at least) relying on python 3.7. Admittedly your prior book does have extensive and useful dev environment set-up instructions, but not this one.

I have python 3.8 installed on my system as the user default. Therefore, the `piplock` file will default to:

```yaml
[requires]
python_version = "3.8"
```

When you get to install the psycopg2 package, the error that is thrown is:

```sh
❯ docker-compose exec web pipenv install psycopg2-binary==2.8.3
Warning: Python 3.8 was not found on your system…
Neither 'pyenv' nor 'asdf' could be found to install Python.
You can specify specific versions of Python with:
$ pipenv --python path/to/python
```

I believe the error arises from how the `Dockerfile` and the `piplock` at this point differ, with the `Dockerfile` specifying 3.7. If the `piplock` gets changed manually to 3.7 however, then the install runs as expected. 

A potential guarantee may be adding the `--python 3.7` on pipenv creation.

**Comment by wsvincent** [comment]
Yes, I think you are correct. I've updated the newer versions of the book to use Python 3.8 but this is a very likely gotcha for newcomers. Thank you for pointing it out. I like your idea of using the `requires` feature; I think I'll use that in the new text!

**Comment by lapulgaatomica** [comment]
> I ran into an error, which I've fixed, but that could be a trap for new users. It stems from having a system install of python 3.8, and the book (sample at least) relying on python 3.7. Admittedly your prior book does have extensive and useful dev environment set-up instructions, but not this one.
> 
> I have python 3.8 installed on my system as the user default. Therefore, the `piplock` file will default to:
> 
> ```yaml
> [requires]
> python_version = "3.8"
> ```
> 
> When you get to install the psycopg2 package, the error that is thrown is:
> 
> ```shell
> ❯ docker-compose exec web pipenv install psycopg2-binary==2.8.3
> Warning: Python 3.8 was not found on your system…
> Neither 'pyenv' nor 'asdf' could be found to install Python.
> You can specify specific versions of Python with:
> $ pipenv --python path/to/python
> ```
> 
> I believe the error arises from how the `Dockerfile` and the `piplock` at this point differ, with the `Dockerfile` specifying 3.7. If the `piplock` gets changed manually to 3.7 however, then the install runs as expected.
> 
> A potential guarantee may be adding the `--python 3.7` on pipenv creation.

I'm not sure what you mean by "adding `--python 3.7` on pipenv creation" can you please explain?

**Comment by DaveParr** [comment]
@lapulgaatomica pipenv is a way of managing environments and dependencies for python. 

https://pypi.org/project/pipenv/

In this particular case, and from memory now almost a year back @wsvincent in his (great) books, I think introduces people following through the work on their computers in a way that encourages them to use pipenv to set up their projects. In this case I was making a (soft) recommendation that for future copies of the book he includes the instruction to run `pipenv --python 3.7` as this will set the project up in a way that, at the time, fixed a dependcy issue with psychopog2. 

If you go the website listed above and look at the usage section on the front page it says:

"Usage Examples:
   Create a new project using Python 3.7, specifically:
   $ pipenv --python 3.7"
   
   this is what I was referring to.
   
   
   Hope that helps :)
