### ISSUE TITLE
book (hard copy) and repo is very different

### ISSUE THREAD

**Issue by SPH73** [wsvincent/djangoforprofessionals#69]
is it possible to get a copy of the latest book? I bought my book at the beginning of August and the code matched but now I see when I want to get clarification the code is different and I can't make sense of it? For example the bookstore_project in chapter 3 now it is called books and has accounts and I have no idea how that came to be?

**Comment by wsvincent** [comment]
Hi @SPH73,

I've added a dedicated repo with the 3.0 code that will match the book. Here is the link: https://github.com/wsvincent/djangoforprofessionals_30

I'm adding a link to the Readme on this repo pointing to it.

-Will

**Comment by SPH73** [comment]
Hi Will,

Thank you so much, that is wonderful. It’s such a fabulous book and I am so glad to own a copy. 

Best,
Sue

**Comment by wsvincent** [comment]
Thank you Sue! Very kind of you to say so :)

-Will
