### ISSUE TITLE
Question on Testing in Chapter 4

### ISSUE THREAD

**Issue by shutteritch** [wsvincent/djangoforprofessionals#72]
I'm a fairly novice coder and even more new to the idea of testing so there might be something really obvious that I'm missing, but my question relates to the steps in chapter 4 for "setUp Method" where we set self.response and remove the test_homepage_url_name.

I understand why we'd want to use `self.response` to avoid repeating code but by using `self.client.get(reverse('home'))` in `setUp()` there are now a handful of tests that will fall down if `reverse('home')` doesn't work and it doesn't seem like it'd be obvious from the pattern of test failures why this happened, as it would when test_homepage_url_name was still a test.

Would it not be better to use `self.client.get('/')` within `setUp()` and add a test to check something like `self.client.get('/') == self.client.get(reverse('home'))` so that if the former worked and the latter didn't, it'd be more clear where the failure is occurring?

**Comment by repcsi** [comment]
I think you can, if there was an issue both solutions would probably point it out. I also added a test that reverse('home') points to / as from my earlier experience this worth checking:

`    def test_checkif_home_is_slash(self):
        response_slash = self.client.get('/')
        self.assertEqual(self.response.content, response_slash.content)`

I'm also curious what @wsvincent thinks about this as he is more experienced.

**Comment by wsvincent** [comment]
Hi @repcsi and @shutteritch, I'm horribly late in response but finishing up the 4.0 update and wanted to weigh in here.

Testing is ultimately subjective. As long as something fails once it will trigger an error so I think there's nothing wrong with also adding a test for `/` if the `home` URL changes. 

In the book we add tests right after doing code and I largely just give the tests and they pass. In reality, I was breaking things as I added new features and added tests along the way so it is unusual to have perfect tests all the time and it is normal and advised to add as many little things as you can think of. You can always have more tests.

Hope that helps! Thank you both for commenting and reading the book :)
