### ISSUE TITLE
Test Fails, Django 3.1.4

### ISSUE THREAD

**Issue by jonolsu** [wsvincent/djangoforprofessionals#74]
I had to change:

`self.assertTemplateUsed(self.response, 'home.html')`

to

`self.assertTemplateUsed('home.html')`

and

`self.assertTemplateUsed(self.response, 'about.html')`

to

`self.assertTemplateUsed('about.html')`

for my tests to pass in Django 3.1.4

These lines can be found at lines 19 and 43 of
https://github.com/wsvincent/djangoforprofessionals/blob/master/ch17-deployment/pages/tests.py
with this commit:
https://github.com/wsvincent/djangoforprofessionals/commit/347e307035abae1ad33bf511fba17553e88f07b7

**Comment by wsvincent** [comment]
Odd. I haven't been able to recreate this. You do need the response as the first argument for [`assertTemplateUsed`.](https://docs.djangoproject.com/en/4.0/topics/testing/tools/#django.test.SimpleTestCase.assertTemplateUsed).

I'll look into this further as I finish the 4.0 update to see if I can spot what's amiss.

Cheers.
