### ISSUE TITLE
Ch18 - Wrong build command on docker-compose.yml

### ISSUE THREAD

**Issue by dmitrymishanov** [wsvincent/djangoforprofessionals#8]
Hello!
Probably "gunicorn bookstore_project.wsgi -b 0.0.0.0:8000"  should be used in both docker-compose.yml and docker-compose-prod.yml. 
And this is how it's presented in the book.

**Comment by wsvincent** [comment]
Yes! A mistake from an earlier version. Now fixed. Thanks for pointing it out :)
