### ISSUE TITLE
Upgrade django-crispy-forms to 1.7.2

### ISSUE THREAD

**Issue by adamchainz** [wsvincent/djangoforprofessionals#9]
To pull in bug fix https://github.com/django-crispy-forms/django-crispy-forms/issues/779 - otherwise invalid form fields are always hidden, which is purty bad UX :)

**Comment by adamchainz** [comment]
As found on a project with @rupertbaker

**Comment by wsvincent** [comment]
Thanks Adam! Agreed. Have updated the source code and the text to reflect this.
